version: '3'
services:
  db:
    container_name: mysql_test
    build: ./db
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - '3333:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin:
    container_name: phpmyadmin_test
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
  web:
    container_name: php_apache_test
    build: ./web
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html
